Revert "ARM: dts: hix5hd2: add wdg node"
This reverts commit 610bd8722ef40b649b51f01045c5d1903f41b583.

"ARM: dts: hix5hd2: add wdg node" causes a build breakage due to
an undefined constatns:

Error: arch/arm/boot/dts/hisi-x5hd2.dtsi:374.22-23 syntax error

(Don't you just looove the dtc error messages? They are so informative!)

Signed-off-by: Olof Johansson <olof@lixom.net>

[ upstream commit: 32bb231845325ca4d19bba414f8883f3e0d6436f ]